# Generated by Django 3.0.7 on 2020-07-02 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200702_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 2, 34, 43, 235115, tzinfo=utc)),
        ),
    ]
